# Site settings
title: Aspiris Pharmaceuticals
subtitle: "Aspiris Pharmaceuticals is a leading global biopharmaceutical company"
author: Aspiris Pharmaceuticals
url: http://www.aspirispharma.github.io
# Contact settings
email: mailto:aspiris.pharmaceuticals@gmail.com
description: "Welcome to Aspiris Pharmaceuticals. We are a leading global biopharmaceutical company that discovers, develops and delivers innovative medicines in areas of unmet medical need."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:aspiris.pharmaceuticals@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Plot no 520, Road No 5,
  - line: SachinG.I.D.G., Sachin,
  - line: Surat-294230, Gujarat, India

# Build settings
markdown: kramdown
permalink: pretty
